### ISSUE TITLE
Correct way to add records to an array

### ISSUE THREAD

**Issue by krishvishal** [BioJulia/XAM.jl#58]
I'm trying to read a BAM file and add only mapped records to an array. But irrespective of the BAM file used the return records array is filled with the same record (the record changes when I change the file but with same file its all filled same record). 

```julia
function read_bam(bam_path)
    rec = []
    reader = open(BAM.Reader, bam_path)
    record = BAM.Record()
    while !eof(reader)
        empty!(record)
        read!(reader, record)
        if BAM.ismapped(record)
            push!(rec, record)
        end
    end
    return rec
end
```

Am I doing something wrong here? Is there a way to achieve this? 

## Your Environment

- Package Version used: 0.3.1
- Julia Version used:  1.7.2
- Operating System and version (desktop or mobile): Ubuntu 20.04

**Comment by jakobnissen** [comment]
The reason your code does not work as expected is that `BAM.Record` is mutable, and that `read!(reader, record)` overwrites `record`. This idiom is useful because it's more efficient as it allows you to not instantiate new records, but reuse the same again and again:

```julia
julia> bam_path = "/home/jakob/code/FormatSpecimens.jl/BAM/bam1.bam"
"/home/jakob/code/FormatSpecimens.jl/BAM/bam1.bam"

julia> records = read_bam(bam_path);

julia> records[1] === records[2] === records[3]
true
```
You can get around this by instead reading into a new record object every time:
```julia
function read_bam(bam_path)
    rec = []
    reader = open(BAM.Reader, bam_path)
    while !eof(reader)
        record = BAM.Record()
        read!(reader, record)
        if BAM.ismapped(record)
            push!(rec, record)
        end
    end
    return rec
end
```
A more idiomatic way of doing the same might be:
```julia
function read_bam(bam_path)
    open(BAM.Reader, bam_path) do reader
        collect(Iterators.filter(BAM.ismapped, reader))
    end
end
```
This works because `BAM.Reader` objects are iterable, and when iterated, returns _distinct_ `Record` objects instead of overwriting the same.
